CREATE DATABASE EMPRESA2
GO
USE EMPRESA2
GO
CREATE TABLE TICKETSH(
TICKET VARCHAR(8) PRIMARY KEY NOT NULL,
FECHA DATE NOT NULL,
IDESTADO INT NOT NULL,
IDCIUDAD INT NOT NULL,
IDTIENDA INT NOT NULL,
IDEMPLEADO INT NOT NULL
)
GO
CREATE TABLE TICKETSD(
TICKET VARCHAR(8) NOT NULL,
IDPRODUCTO INT NOT NULL,
UNIDADES INT NOT NULL,
PRECIO INT NOT NULL
PRIMARY KEY (TICKET,IDPRODUCTO),
FOREIGN KEY (TICKET) REFERENCES TICKETSH(TICKET)
)
GO
CREATE INDEX IDX_IDESTADO ON TICKETSH(IDESTADO)
CREATE INDEX IDX_IDTIENDA ON TICKETSH(IDTIENDA)
CREATE INDEX IDX_IDEMPLEADO ON TICKETSH(IDEMPLEADO)

GO
DELETE FROM TICKETSD
DELETE FROM TICKETSH
GO
SELECT * FROM TICKETSH
SELECT * FROM TICKETSD
GO
SELECT * FROM TICKETSH WHERE TICKET = '00000001'
SELECT * FROM TICKETSD WHERE TICKET = '00000001'