--CREACION BD1
CREATE DATABASE BD1
GO
USE BD1
GO
CREATE TABLE CLIENTES(
CTE INT NOT NULL,
NOMBRE NVARCHAR(30),
DOMICILIO NVARCHAR(50))
GO
CREATE TABLE EMPLEADOS(
EMP INT NOT NULL,
NOMBRE NVARCHAR(30),
DOMICILIO NVARCHAR(50),
TELEFONO NCHAR(10))
GO
CREATE TABLE VENTAS(
FOLIO INT NOT NULL,
FECHA DATE,
CTE INT NOT NULL,
EMP INT NOT NULL)
GO
ALTER TABLE CLIENTES ADD
CONSTRAINT PK_CLIENTES PRIMARY KEY (CTE)
GO
ALTER TABLE EMPLEADOS ADD
CONSTRAINT PK_EMPLEADOS PRIMARY KEY (EMP)
GO
ALTER TABLE VENTAS ADD
CONSTRAINT PK_VENTAS PRIMARY KEY (FOLIO)
GO
ALTER TABLE VENTAS ADD
CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (CTE) REFERENCES CLIENTES (CTE),
CONSTRAINT FK_VENTAS_EMPLEADOS FOREIGN KEY (EMP) REFERENCES EMPLEADOS (EMP)
GO

--CREACION BD2
CREATE DATABASE BD2
GO
USE BD2
GO
CREATE TABLE PRODUCTOS(
PROD INT NOT NULL,
NOMBRE NVARCHAR(30),
CAT INT NOT NULL,
PRECIO MONEY NOT NULL)
GO
CREATE TABLE CATEGORIAS(
CAT INT NOT NULL,
NOMBRE NVARCHAR(30))
GO
CREATE TABLE VENTAS(
FOLIO INT NOT NULL,
FECHA DATE,
PROD INT NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO MONEY)
GO
ALTER TABLE PRODUCTOS ADD 
CONSTRAINT PK_PRODUCTOS PRIMARY KEY (PROD)
GO
ALTER TABLE CATEGORIAS ADD 
CONSTRAINT PK_CATEGORIAS PRIMARY KEY (CAT)
GO
ALTER TABLE VENTAS ADD 
CONSTRAINT PK_VENTAS PRIMARY KEY (FOLIO)
GO
ALTER TABLE PRODUCTOS ADD 
CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (CAT) REFERENCES CATEGORIAS (CAT)
GO
ALTER TABLE VENTAS ADD 
CONSTRAINT FK_VENTAS_PRODUCTOS FOREIGN KEY (PROD) REFERENCES PRODUCTOS (PROD)
GO

-- 1.- Dar de alta al IS ALMA pueda apagar el servidor con el comando SHUTDOWN.
CREATE LOGIN ALMA WITH PASSWORD = '123'
GO
sp_AddSRVRoleMember ALMA, ServerAdmin
GO

-- 2.- Dar de alta al IS JUAN para que pueda auxiliar en la administración de 
-- inicios de sesión, que pueda dar de alta inicios de sesión y cambiar password.
CREATE LOGIN JUAN WITH PASSWORD = '123'
GO
sp_AddSRVRoleMember JUAN, SecurityAdmin
GO

-- 3.- Dar de alta al IS JOSE y configurarlo para que tenga las mismas
-- características que el inicio de sesión SA.
CREATE LOGIN JOSE WITH PASSWORD = '123'
GO
sp_AddSRVRoleMember JOSE, SysAdmin
GO

-- 4.- Dar de alta al IS PEDRO para que pueda seleccionar y modificar 
-- (I/U/D) todas las tablas de las bases de datos BD1 y BD2.
CREATE LOGIN PEDRO WITH PASSWORD = '123'
GO
USE BD1
CREATE USER PEDRO FOR LOGIN PEDRO
GRANT SELECT,INSERT,UPDATE,DELETE ON CLIENTES TO PEDRO
GRANT SELECT,INSERT,UPDATE,DELETE ON EMPLEADOS TO PEDRO
GRANT SELECT,INSERT,UPDATE,DELETE ON VENTAS TO PEDRO
GO
USE BD2
CREATE USER PEDRO FOR LOGIN PEDRO
GRANT SELECT,INSERT,UPDATE,DELETE ON PRODUCTOS TO PEDRO
GRANT SELECT,INSERT,UPDATE,DELETE ON CATEGORIAS TO PEDRO
GRANT SELECT,INSERT,UPDATE,DELETE ON VENTAS TO PEDRO
GO

-- 5.- Dar de alta al IS NORA Y PERLA para que puedan crear todos los objetos en BD1.
CREATE LOGIN NORA WITH PASSWORD = '123'
CREATE LOGIN PERLA WITH PASSWORD = '123'
GO
USE BD1
CREATE USER NORA FOR LOGIN NORA
CREATE USER PERLA FOR LOGIN PERLA
GO
sp_AddRoleMember db_ddlAdmin, NORA
GO
sp_AddRoleMember db_ddlAdmin, PERLA
GO

-- 6.- En la base de datos BD1 crear la función CONSULTA y darle permiso para que pueda
-- seleccionar solo las 2 primeras columnas de cada tabla. A los IS NORA Y PERLA creados
-- en el punto 6, agregarlos en la función CONSULTA de la base de datos BD1.
USE BD1
GO
sp_AddRole CONSULTA
GO
GRANT SELECT ON CLIENTES(CTE,NOMBRE) TO CONSULTA
GRANT SELECT ON EMPLEADOS(EMP,NOMBRE) TO CONSULTA
GRANT SELECT ON VENTAS(FOLIO,FECHA) TO CONSULTA
GO
sp_AddRoleMember CONSULTA, NORA
GO
sp_AddRoleMember CONSULTA, PERLA
GO

-- 7.- Dar de alta al IS CARLOS y que pueda insertar y eliminar datos en la BD2, 
-- además pueda crear vistas y tablas en la misma base de datos.
CREATE LOGIN CARLOS WITH PASSWORD = '123'
GO
USE BD2
CREATE USER CARLOS FOR LOGIN CARLOS
GO
GRANT INSERT,DELETE ON PRODUCTOS TO CARLOS
GRANT INSERT,DELETE ON CATEGORIAS TO CARLOS
GRANT INSERT,DELETE ON VENTAS TO CARLOS
GRANT CREATE VIEW, CREATE TABLE TO CARLOS
GRANT ALTER ON SCHEMA::DBO TO CARLOS
GO

-- 8.- Es necesario crear los IS siguientes: asesor01, asesor02,… asesor80. 
-- Crear un procedimiento almacenado que los genere automáticamente con la 
-- característica que le cambien el password la primera vez que se conecten.
USE BD1
GO
CREATE PROC SP_ASESORES AS
BEGIN
	DECLARE @ID INT, @Nombre NVARCHAR(8), @Codigo NVARCHAR(200)
	SELECT @ID = 01
	WHILE @ID <= 80
	BEGIN
		IF @ID < 10
			SELECT @Nombre = 'asesor0'+STR(@ID,1)
		ELSE
			SELECT @Nombre = 'asesor'+STR(@ID,2)

		SELECT @Codigo = 'CREATE LOGIN '+@Nombre+' WITH PASSWORD = ''123'' MUST_CHANGE, CHECK_EXPIRATION = ON'
		EXEC(@Codigo)
		SELECT @ID = @ID+1
	END
END
GO
EXEC SP_ASESORES
GO

-- 9.- De los IS creados en el punto 8, crear un procedimiento almacenado que
-- los de alta como usuario en la base de datos BD1.
USE BD1
GO
CREATE PROC SP_ALTA_ASESORES AS
BEGIN
	DECLARE @ID INT, @Nombre NVARCHAR(8), @Codigo NVARCHAR(200)
	SELECT @ID = 01
	WHILE @ID <= 80
	BEGIN
		IF @ID < 10
			SELECT @Nombre = 'asesor0'+STR(@ID,1)
		ELSE
			SELECT @Nombre = 'asesor'+STR(@ID,2)

		SELECT @Codigo = 'USE BD1 CREATE USER '+@Nombre+' FOR LOGIN '+@Nombre
		EXEC(@Codigo)
		SELECT @ID = @ID+1
	END
END
GO
EXEC SP_ALTA_ASESORES
GO

-- 10.- En la base de datos northwind cambiar el esquema DBO de todas
-- tablas por el esquema RECURSOS utilizando un procedimiento almacenado.
USE Northwind
GO
CREATE SCHEMA RECURSOS
GO
CREATE PROC SP_DBOTORECURSOS AS
BEGIN
	DECLARE @TablaID INT, @Codigo NVARCHAR(500)

	SELECT @TablaID = MIN(object_id)
	FROM sys.tables
	WHERE name NOT LIKE 'sysdiagrams'

	WHILE @TablaID IS NOT NULL
	BEGIN
		DECLARE @Tabla NVARCHAR(50)
		SELECT @Tabla = name
		FROM sys.tables
		WHERE object_id = @TablaID

		SELECT @Codigo = 'ALTER SCHEMA RECURSOS TRANSFER DBO.'+@Tabla

		EXEC(@Codigo)

		SELECT @TablaID = MIN(object_id)
		FROM sys.tables
		WHERE name NOT LIKE 'sysdiagrams'
		AND @TablaID < object_id
	END
END
GO
EXEC SP_DBOTORECURSOS











