CREATE DATABASE HOSPITALES2
GO
USE HOSPITALES2
GO
--CREACION DE TABLAS
CREATE TABLE ZONAS(
ZONAID INT NOT NULL,
NOMBRE NVARCHAR(40) NOT NULL)
GO
CREATE TABLE HOSPITALES(
HOSPID INT NOT NULL,
NOMBRE NVARCHAR(40) NOT NULL,
ZONAID INT NOT NULL)
GO
CREATE TABLE CONSULTORIOS(
CONID INT NOT NULL, 
NOMBRE NVARCHAR(40) NOT NULL,
HOSPID INT NOT NULL)
GO
CREATE TABLE CITAS(
CITA INT NOT NULL,
FECHA DATETIME NOT NULL,
PESO INT NOT NULL,
ESTATURA INT NOT NULL,
PRESION INT NOT NULL,
OBSERVACIONES NVARCHAR(100) NULL,
CONID INT NOT NULL)
GO
--LLAVES PRIMARIAS
ALTER TABLE ZONAS ADD CONSTRAINT PK_ZONAS PRIMARY KEY (ZONAID)
ALTER TABLE HOSPITALES ADD CONSTRAINT PK_HOSPITALES PRIMARY KEY (HOSPID)
ALTER TABLE CONSULTORIOS ADD CONSTRAINT PK_CONSULTORIOS PRIMARY KEY (CONID)
ALTER TABLE CITAS ADD CONSTRAINT PK_CITAS PRIMARY KEY (CITA)
GO
--LLAVES EXTERNAS
ALTER TABLE HOSPITALES ADD
CONSTRAINT FK_HOSPITALES_ZONAID FOREIGN KEY (ZONAID) REFERENCES ZONAS (ZONAID)
GO
ALTER TABLE CONSULTORIOS ADD
CONSTRAINT FK_CONSULTORIOS_HOSPID FOREIGN KEY (HOSPID) REFERENCES HOSPITALES (HOSPID)
GO
ALTER TABLE CITAS ADD
CONSTRAINT FK_CITAS_CONID FOREIGN KEY (CONID) REFERENCES CONSULTORIOS (CONID)
GO
--VALORES DEFAULT
ALTER TABLE CITAS ADD
CONSTRAINT DC_CITAS_OBS DEFAULT ('SIN OBSERVACIONES') FOR OBSERVACIONES
GO
--COMPROBACION
ALTER TABLE CITAS ADD
CONSTRAINT CC_CITAS_PESO CHECK (PESO > 0),
CONSTRAINT CC_CITAS_PRESION CHECK (PRESION > 0),
CONSTRAINT CC_CITAS_ESTATURA CHECK (ESTATURA > 0)
GO