USE HOSPITALES2
GO
-- FAMILIA DE VISTAS
CREATE VIEW VW_HOSPITALES AS
SELECT H.HOSPID, HOSPNOMBRE = H.NOMBRE,
Z.ZONAID,ZONNOMBRE = Z.NOMBRE
FROM HOSPITALES H
INNER JOIN ZONAS Z ON Z.ZONAID=H.ZONAID
GO
CREATE VIEW VW_CONSULTORIOS AS
SELECT C.CONID,CONSNOMBRE = C.NOMBRE, H.*
FROM CONSULTORIOS C
INNER JOIN VW_HOSPITALES H ON H.HOSPID=C.HOSPID
GO
CREATE VIEW VW_CITAS AS
SELECT CI.CITA, CI.FECHA, CI.PESO, CI.ESTATURA, CI.PRESION, CI.OBSERVACIONES,
C.*
FROM CITAS CI 
INNER JOIN VW_CONSULTORIOS C ON C.CONID=CI.CONID
GO
