USE Northwind
GO
CREATE PROC SP_JEFES
@EMP INT,@ER VARCHAR(500) OUTPUT AS
DECLARE @JEFE INT,@JEFENOMBRE VARCHAR(50)
SELECT @JEFE = ReportsTo FROM Employees WHERE EmployeeID = @EMP
SELECT @ER = ''
WHILE (@JEFE IS NOT NULL)
BEGIN
	SELECT @JEFENOMBRE = FirstName FROM Employees WHERE EmployeeID = @JEFE
	SELECT @ER = @ER + @JEFENOMBRE + ', '
	SELECT @JEFE = ReportsTo FROM Employees WHERE EmployeeID = @JEFE
END
GO
DECLARE @ER VARCHAR(500)
EXEC SP_JEFES 6,@ER OUTPUT
SELECT JEFES = @ER
