CREATE DATABASE Empresa

USE Empresa

CREATE TABLE Marcas(
ID INT NOT NULL,
Marca VARCHAR(50) NOT NULL,
Vig CHAR NOT NULL)

ALTER TABLE Marcas ADD CONSTRAINT PK_MARCAS PRIMARY KEY(ID)

INSERT INTO Marcas VALUES(1,'ADOLFO DOMINGUEZ','T')
INSERT INTO Marcas VALUES(2,'ALEXANDER MCQUEEN','T')
INSERT INTO Marcas VALUES(3,'ALLSAINTS','T')
INSERT INTO Marcas VALUES(4,'AMI','F')
INSERT INTO Marcas VALUES(5,'ARMANI EXCHANGE','T')
INSERT INTO Marcas VALUES(6,'BALENCIAGA','T')
INSERT INTO Marcas VALUES(7,'BALMAIN','T')
INSERT INTO Marcas VALUES(8,'BOGGI','T')
INSERT INTO Marcas VALUES(9,'HUGO BOSS','T')
INSERT INTO Marcas VALUES(10,'ADIDAS','T')
INSERT INTO Marcas VALUES(11,'CALVIN KLEIN','T')
INSERT INTO Marcas VALUES(12,'CAMASHA','T')
INSERT INTO Marcas VALUES(13,'CATERPILLAR','T')
INSERT INTO Marcas VALUES(14,'CECO','T')
INSERT INTO Marcas VALUES(15,'CHAMPION','T')
INSERT INTO Marcas VALUES(16,'DOCKER','T')
INSERT INTO Marcas VALUES(17,'EVERLAST','T')
INSERT INTO Marcas VALUES(18,'FERRIONI','T')
INSERT INTO Marcas VALUES(19,'JACK & JONES','T')
INSERT INTO Marcas VALUES(20,'MICHAEL KORS','T')
INSERT INTO Marcas VALUES(21,'NAUTICA','T')
INSERT INTO Marcas VALUES(22,'MYST','T')
INSERT INTO Marcas VALUES(23,'OAS','F')
INSERT INTO Marcas VALUES(24,'NIKE','T')
INSERT INTO Marcas VALUES(25,'POLO','T')
INSERT INTO Marcas VALUES(26,'PUMA','T')
INSERT INTO Marcas VALUES(27,'ROOSEVELT','T')
INSERT INTO Marcas VALUES(28,'SALOMON','T')
INSERT INTO Marcas VALUES(29,'SANSABELT','T')
INSERT INTO Marcas VALUES(30,'SFERA','T')
INSERT INTO Marcas VALUES(31,'SKECHERS','T')
INSERT INTO Marcas VALUES(32,'THAT!','T')
INSERT INTO Marcas VALUES(33,'TOMMY HILFIGER','T')
INSERT INTO Marcas VALUES(34,'UNDER ARMOUR','T')
INSERT INTO Marcas VALUES(35,'YAKUZA','T')


SELECT * FROM Marcas

SELECT * FROM Marcas
WHERE Vig = 'T'
ORDER BY Marca