; INTEGRANTES:
; AVILES BRAVO CESAR AMADO
; BELTRAN MEDINA CARLOS DANIEL
; BELTRAN ONTIVEROS KAREN VALERIA
; GARCIA SANCHEZ SERGIO JESUS
; VALENZUELA BERRELLEZA CESAR JESUS

TITLE LEER UN CARACTER, SI ES MAYUSCULA CONVERTIR A MINUSCULA Y VICEVERSA, SI NO ES LETRA MANDAR MENSAJE DE INVALIDO
.MODEL SMALL
.STACK 100H
.DATA
    MSG1 DB 10,13,'DAME UNA LETRA :$'
    MSG2 DB 10,13,'LA MINUSCULA ES :$'
    MSG3 DB 10,13,'LA MAYUSCULA ES :$'
    MSG4 DB 10,13,'CHAR INVALIDO, INTENTE DE NUEVO $'
    MSG5 DB 10,13,'?QUIERES CONTINUAR (S/N)?$'
    CHAR DB 0
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
INICIO:
    ;PIDE UN CHAR
    MOV AH,9
    LEA DX,MSG1
    INT 21H
    
    ;LEE EN EL CARACTER
    MOV AH,01
    INT 21H
    
    ;VERIFICA SI ES MINUSCULA
    CMP AL,'a'
    JL CHECA_MAYUSCULA
    CMP AL,'z'
    JG INVALIDO
MINUSCULA:
    ;CONVIERTE A MAYUSCULA
    SUB AL, 32
    MOV CHAR,AL
    LEA DX,MSG3
    JMP DESPLIEGA
CHECA_MAYUSCULA:
    CMP AL,'A'
    JL INVALIDO
    CMP AL,'Z'
    JG INVALIDO
MAYUSCULA:
    ;CONVIERTE A MINUSCULA
    ADD AL,32
    MOV CHAR,AL
    LEA DX,MSG2
DESPLIEGA:
    MOV AH,9
    INT 21H
    MOV DL,CHAR
    MOV AH,2
    INT 21H
    JMP VERIFICA
INVALIDO:
    LEA DX,MSG4
    MOV AH,9
    INT 21H
    LOOP INICIO
VERIFICA:
    LEA DX,MSG5
    MOV AH,9
    INT 21H
    MOV AH,1
    INT 21H
    CMP AL,'s'
    JE INICIO
    CMP AL,'S'
    JE INICIO
    CMP AL,'Y'
    JE INICIO
    CMP AL,'y'
    JE INICIO
FIN:  
    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN
    
   
