; INTEGRANTES:
; AVILES BRAVO CESAR AMADO
; BELTRAN MEDINA CARLOS DANIEL
; BELTRAN ONTIVEROS KAREN VALERIA
; GARCIA SANCHEZ SERGIO JESUS
; VALENZUELA BERRELLEZA CESAR JESUS

TITLE DESPLIEGA OCTAL EN DX
.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC 
    MOV AX, @DATA
    MOV DS, AX
    
    MOV DX, 65432
    XOR CX, CX
    MOV AX, DX
    
 CICLO:
    XOR DX, DX 
    MOV BX, 8
    DIV BX
    INC CX 
    PUSH DX 
    CMP AX, 0 
    JNE CICLO
    
DISPLAY:
    POP DX
    OR DL, 30H
    MOV AH,2
    INT 21H
    LOOP DISPLAY
    
    MOV AH, 4CH 
    INT 21H
MAIN ENDP 
    END MAIN