; INTEGRANTES:
; AVILES BRAVO CESAR AMADO
; BELTRAN MEDINA CARLOS DANIEL
; BELTRAN ONTIVEROS KAREN VALERIA
; GARCIA SANCHEZ SERGIO JESUS
; VALENZUELA BERRELLEZA CESAR JESUS

TITLE LEER UN # HEXADECIMAL DE HASTA 4 CIFRAS, ALMACENAR EN NUM1 Y DESPLEGAR
.MODEL SMALL
.STACK 100H
.DATA
    MSG1 DB 10,13,'DAME UN NUMERO HEXADECIMAL DE 4 CIFRAS:$'
    MSG2 DB 10,13,'EL NUMERO FUE:$'
    MSG3 DB 10,13,'NUMERO INVALIDO, INTENTA DE NUEVO$'
    NUM1 DW 0
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
INICIO:
    MOV NUM1,0
    ;PIDE NUMERO HEXADECIMAL
    LEA DX,MSG1
    MOV AH,9
    INT 21H
    
    MOV CX,4
    ;LEER CHAR
CICLO:
    ;LEER CHAR
    MOV AH,1
    INT 21H
    
    ;VERIFICAR SI ES DIGITO
    CMP AL,'0'
    JL ERROR
    CMP AL, '9'
    JG CHECA_MAYUSCULA
    ;SI NO SALTO, ES DIGITO
DIGITO:
    ;CONVIERTE DE ASCII A NUMERO
    AND AL,0FH
    JMP GUARDA
CHECA_MAYUSCULA:
    ;VERIFICA SI ES MAYUSCULA
    CMP AL,'A'
    JL ERROR
    CMP AL,'F'
    JG CHECA_MINUSCULA
MAYUSCULA:
    ;CONVIERTE DE MAYUSCULA A NUMERO
    SUB AL,55
    JMP GUARDA
CHECA_MINUSCULA:
    ;VERIFICAR SI ES MINUSCULA
    CMP AL,'a'
    JL ERROR
    CMP AL,'f'
    JG ERROR
    ;SI NO SALTA, FUE MINUSCULA
MINUSCULA:
    ;CONVERTIR DE MINUSCULA A NUMERO
    SUB AL,87
GUARDA:
    ;HACER ESPACIO EN NUM1
    PUSH CX
    MOV CL,4
    SHL NUM1,CL
    POP CX
    ;EXTENDER EL NUMERO DE BYTE A WORD PARA QUE SEAN COMPATIBLES AX CON NUM1
    CBW
    OR NUM1,AX
    LOOP CICLO
    JMP FIN
ERROR:
    LEA DX,MSG3
    MOV AH,9
    INT 21H
    JMP INICIO

FIN:  
    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN
    
   
