; INTEGRANTES:
; AVILES BRAVO CESAR AMADO
; BELTRAN MEDINA CARLOS DANIEL
; BELTRAN ONTIVEROS KAREN VALERIA
; GARCIA SANCHEZ SERGIO JESUS
; VALENZUELA BERRELLEZA CESAR JESUS

TITLE LEER NUMERO DECIMAL DE 5 CIFRAS Y DEJAR EN BX
.MODEL SMALL
.STACK 100H
.DATA
    MSG DB 'Dame un numero decimal: $'  
.CODE
MAIN PROC

    MOV AX, @DATA
    MOV DS, AX
    
    ;DESPLEGAR MENSAJE
    MOV AH, 9
    LEA DX, MSG
    INT 21H
    
    ;LIMPIAR BX, PARA INICIALIZARLO
    XOR BX, BX
    
    ;LEER 5 DIGITOS
    MOV CX, 5
    
CICLO:
    MOV AX, 10
    MUL BX
    
    ;EL RESULTADO DE LA MULTIPLICACION QUEDA EN DX:AX, SOLO TOMARE LO DE AX Y DESCARTO LA PARTE ALTA
    MOV BX, AX
    
    ;LEER 1 CHAR
    MOV AH, 1
    INT 21H
    
    ;CONVERTIRLO DE CHAR A NUMERO
    AND AL, 0FH
    
    ;EXTENDER AL A AX
    XOR AH, AH
    
    ;ACUMULAR EL NUMERO LEIDO CON LO QUE HAY EN BX
    ADD BX, AX
    
    LOOP CICLO   
    
    MOV AH, 4CH
    INT 21H

MAIN ENDP
    END MAIN