; INTEGRANTES:
; AVILES BRAVO CESAR AMADO
; BELTRAN MEDINA CARLOS DANIEL
; BELTRAN ONTIVEROS KAREN VALERIA
; GARCIA SANCHEZ SERGIO JESUS
; VALENZUELA BERRELLEZA CESAR JESUS

TITLE LEER DOS NUMEROS BINARIOS DE 8 BITS Y DESPLEGAR LA RESTA
.MODEL SMALL
.STACK 100H
.DATA
    NUM1 DB 0
    NUM2 DB 0
    RESTA DB 0
    MSG1 DB 'DAME UN NUMERO BINARIO DE 8 BITS: $'
    MSG2 DB 10,13,'DAME OTRO NUMERO BINARIO DE 8 BITS: $'
    MSG3 DB 10,13,'LA RESTA ES: $'
.CODE
MAIN PROC 
    MOV AX, @DATA
    MOV DS, AX
    
    ;LEER NUESTRO PRIMER NUMERO 
    LEA DX,MSG1
    MOV AH, 9
    INT 21H
    
    ;INICIALIZAR BH, PARA ALMACENAR EL NUMERO TEMPORALMENTE
    XOR BH,BH
    MOV CX,8

CICLO:
    ;HACER ESPACIO EN BH
    SHL BH,1
    
    ;LEER CHAR
    MOV AH,1
    INT 21H
    
    ;CONVERTIR DE CHAR A NUMERO
    AND AL,0FH
    
    ;METER A BH
    OR BH,AL
    LOOP CICLO
    MOV NUM1,BH
    
    MOV CX,8
    
    ;LEER SEGUNDO NUMERO BINARIO DE 8 BITS
    LEA DX,MSG2
    MOV AH,9
    INT 21H
    
    ;INICIALIZAR BH, PARA ALMACENAR EL NUMERO TEMPORALMENTE
    XOR BH,BH
    
CICLO2:
    ;HACER ESPACIO EN BH
    SHL BH,1
    
    ;LEER CHAR
    MOV AH,1
    INT 21H
    
    ;CONVERTIR DE CHAR A NUMERO
    AND AL,0FH
    
    ;METERLO A BH
    OR BH,AL
    LOOP CICLO2
    MOV NUM2,BH
    
    ;HACER LA RESTA
    MOV BH,NUM1
    SUB BH,NUM2
    MOV RESTA,BH
    
    ;DESPLEGAR LA RESTA
    LEA DX,MSG3
    MOV AH,9
    INT 21H
    
    ;DESPLEGAR LA RESTA
    MOV CX, 8
    
DISP:
    ;INICIALIZO DL EN 0
    XOR DL,DL
    ;SACO 1 BIT DE NUM 1 Y LO METO A DL 
    ROL RESTA,1
    RCL DL,1
    ;CONVIERTO DE NUM A CHAR
    OR DL,30H
    ;DESPLIEGO BIT
    MOV AH,2
    INT 21H
    LOOP DISP
    
    MOV AH, 4CH 
    INT 21H
MAIN ENDP 
    END MAIN