; INTEGRANTES:
; AVILES BRAVO CESAR AMADO
; BELTRAN MEDINA CARLOS DANIEL
; BELTRAN ONTIVEROS KAREN VALERIA
; GARCIA SANCHEZ SERGIO JESUS
; VALENZUELA BERRELLEZA CESAR JESUS

TITLE LEER DOS NUMERO DECIMAL DE 5 CIFRAS SUMARLOS Y MOSTRARLOS
.MODEL SMALL
.STACK 100H
.DATA
    MSG DB 'Dame un numero decimal: $'
    MSG2 DB 10,13,'Dame otro numero decimal: $'
    SALTO DB 10,13,'LA SUMA ES: $'
    DEC1 DW ?
    DEC2 DW ?
    SUMA DW ?
.CODE
MAIN PROC

    MOV AX, @DATA
    MOV DS, AX
    
    ;LEER DEC1
    ;DESPLEGAR MENSAJE
    MOV AH, 9
    LEA DX, MSG
    INT 21H
    
    ;LIMPIAR BX, PARA INICIALIZARLO
    XOR BX, BX
    
    ;LEER 5 DIGITOS
    MOV CX, 5
    
CICLO:
    MOV AX, 10
    MUL BX
    
    ;EL RESULTADO DE LA MULTIPLICACION QUEDA EN DX:AX, SOLO TOMARE LO DE AX Y DESCARTO LA PARTE ALTA
    MOV BX, AX
    
    ;LEER 1 CHAR
    MOV AH, 1
    INT 21H
    
    ;CONVERTIRLO DE CHAR A NUMERO
    AND AL, 0FH
    
    ;EXTENDER AL A AX
    XOR AH, AH
    
    ;ACUMULAR EL NUMERO LEIDO CON LO QUE HAY EN BX
    ADD BX, AX
    
    LOOP CICLO   
    MOV DEC1,BX
    
    
    
    ;LEER DEC2
    ;DESPLEGAR MENSAJE
    MOV AH, 9
    LEA DX, MSG2
    INT 21H
    
    ;LIMPIAR BX, PARA INICIALIZARLO
    XOR BX, BX
    
    ;LEER 5 DIGITOS
    MOV CX, 5
    
CICLO2:
    MOV AX, 10
    MUL BX
    
    ;EL RESULTADO DE LA MULTIPLICACION QUEDA EN DX:AX, SOLO TOMARE LO DE AX Y DESCARTO LA PARTE ALTA
    MOV BX, AX
    
    ;LEER 1 CHAR
    MOV AH, 1
    INT 21H
    
    ;CONVERTIRLO DE CHAR A NUMERO
    AND AL, 0FH
    
    ;EXTENDER AL A AX
    XOR AH, AH
    
    ;ACUMULAR EL NUMERO LEIDO CON LO QUE HAY EN BX
    ADD BX, AX
    
    LOOP CICLO2  
    MOV DEC2,BX
    
    ;SUMA LOS NUMEROS
    MOV AX,DEC1
    ADD AX,DEC2
    MOV SUMA,AX
    
    ;DESPLEGAR LA SUMA
    MOV AH, 9
    LEA DX, SALTO
    INT 21H
    
    MOV AX,SUMA
    XOR CX,CX ;LIMPIA CX
CICLO3:
    XOR DX,DX ;LIMPIA DX
    MOV BX,10
    DIV BX
    ADD DL,30H ;CONVIERTE NUMERO A CHAR 
    
    PUSH DX ;GUARDA EL NUMERO EN LA PILA
    INC CX
    CMP AX,0
   
    JNE CICLO3
    
MOSTRAR:
    XOR DX,DX
    POP DX
    MOV AH,2
    INT 21H
    LOOP MOSTRAR
    
    MOV AH, 4CH
    INT 21H

MAIN ENDP
    END MAIN