; INTEGRANTES:
; AVILES BRAVO CESAR AMADO
; BELTRAN MEDINA CARLOS DANIEL
; BELTRAN ONTIVEROS KAREN VALERIA
; GARCIA SANCHEZ SERGIO JESUS
; VALENZUELA BERRELLEZA CESAR JESUS

TITLE LEE DOS NUMEROS EN BINARIO, LOS SUMA Y LOS DESPIEGLA RESULTADO
.MODEL SMALL
.STACK 100H 
.DATA
    NUM1 DB 0
    NUM2 DB 0 
    SUMA DB 0
    MSG1 DB 'DAME UN NUMERO DE 8 BTIS:$'
    MSG2 DB 10,13,'DAME OTRO NUMERO BINARIO DE 8 BITS:$'
    MSG3 DB 10,13,'LA SUMA ES:$'
    MSG4 DB 10,13,'LA RESTA ES:$'
    MSG5 DB 10,13,'LA MULTIPLICACION ES:$'
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX

    ;LEER NUESTRO PRIMER NUMERO 
    LEA DX,MSG1
    MOV AH, 9
    INT 21H
    
    ;INICIALIZAR BH, PARA ALMACENAR EL NUMERO TEMPORALMENTE
    XOR BH,BH
    MOV CX,8

CICLO:
    ;HACER ESPACIO EN BH
    SHL BH,1
    
    ;LEER CHAR
    MOV AH,1
    INT 21H
    
    ;CONVERTIR DE CHAR A NUMERO
    AND AL,0FH
    
    ;METER A BH
    OR BH,AL
    LOOP CICLO
    MOV NUM1,BH
    
    MOV CX,8
    
    ;LEER SEGUNDO NUMERO BINARIO DE 8 BITS
    LEA DX,MSG2
    MOV AH,9
    INT 21H
    
    ;INICIALIZAR BH, PARA ALMACENAR EL NUMERO TEMPORALMENTE
    XOR BH,BH
    
CICLO2:
    ;HACER ESPACIO EN BH
    SHL BH,1
    
    ;LEER CHAR
    MOV AH,1
    INT 21H
    
    ;CONVERTIR DE CHAR A NUMERO
    AND AL,0FH
    
    ;METERLO A BH
    OR BH,AL
    LOOP CICLO2
    MOV NUM2,BH
    
    ;HACER LA SUMA
    MOV BH,NUM1
    ADD BH,NUM2
    MOV SUMA,BH
    
    ;DESPLEGAR LA SUMA
    LEA DX,MSG3
    MOV AH,9
    INT 21H
    
    ;DESPLEGAR LA SUMA
    MOV CX, 8

CICLO_DISP:
    ;INICIALIZO DL EN 0
    XOR DL,DL
    ;SACO 1 BIT DE NUM 1 Y LO METO A DL 
    ROL SUMA,1
    RCL DL,1
    ;CONVIERTO DE NUM A CHAR
    OR DL,30H
    ;DESPLIEGO BIT
    MOV AH,2
    INT 21H
    LOOP CICLO_DISP
    
    ;HACER LA RESTA
    MOV BH,NUM1
    SUB BH,NUM2
    MOV SUMA,BH
    
    ;DESPLEGAR LA RESTA
    LEA DX,MSG4
    MOV AH,9
    INT 21H
    
    ;DESPLEGAR LA RESTA
    MOV CX, 8
    
CICLO_DISP2:
    ;INICIALIZO DL EN 0
    XOR DL,DL
    ;SACO 1 BIT DE NUM 1 Y LO METO A DL 
    ROL SUMA,1
    RCL DL,1
    ;CONVIERTO DE NUM A CHAR
    OR DL,30H
    ;DESPLIEGO BIT
    MOV AH,2
    INT 21H
    LOOP CICLO_DISP2
   
    
  
        
    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN