USE MASTER
CREATE LOGIN CESAR WITH PASSWORD = '123'
USE VENTAS
CREATE USER CESAR FOR LOGIN CESAR
GO
sp_addrolemember db_DataReader,CESAR
GO
sp_addrolemember db_DataWriter,CESAR
GO
sp_addrolemember db_ddlAdmin,CESAR
GO
GRANT EXECUTE TO CESAR

USE MASTER
CREATE LOGIN CARLOS WITH PASSWORD = '123'
USE VENTAS
CREATE USER CARLOS FOR LOGIN CESAR
GO
sp_addrolemember db_owner,CARLOS
GO

USE MASTER
CREATE LOGIN KAREN WITH PASSWORD = '123'
USE VENTAS
CREATE USER KAREN FOR LOGIN KAREN
GO
sp_addrolemember db_DataReader,KAREN
GRANT EXECUTE TO KAREN
GRANT SELECT,DELETE ON Articulos TO KAREN
GRANT SELECT ON Familias TO KAREN
GO